$cargo nextest run 50_000_orchard_to_orchard     Blocking waiting for file lock on build directory    Compiling zingolib v0.2.0 (/home/cupress/ZINGO/libs/pr_review/zingolib)    Compiling darkside-tests v0.1.0 (/home/cupress/ZINGO/libs/pr_review/darkside-tests)    Compiling zingo-cli v0.2.0 (/home/cupress/ZINGO/libs/pr_review/zingocli)    Compiling libtonode-tests v0.2.0 (/home/cupress/ZINGO/libs/pr_review/libtonode-tests)     Finished `test` profile [optimized] target(s) in 54.26s     Starting 1 test across 18 binaries (328 skipped)         FAIL [  34.323s] libtonode-tests::chain_generics chain_generics::simpool_change_50_000_orchard_to_orchard
--- STDOUT:              libtonode-tests::chain_generics chain_generics::simpool_change_50_000_orchard_to_orchard ---

running 1 test
test chain_generics::simpool_change_50_000_orchard_to_orchard ... FAILED

failures:

failures:
    chain_generics::simpool_change_50_000_orchard_to_orchard

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 42 filtered out; finished in 34.31s

--- STDERR:              libtonode-tests::chain_generics chain_generics::simpool_change_50_000_orchard_to_orchard ---
thread 'chain_generics::simpool_change_50_000_orchard_to_orchard' panicked at /home/cupress/.cargo/git/checkouts/librustzcash-2a71d81ac8756eb7/4487437/zcash_client_backend/src/data_api/wallet.rs:1266:22:
Wallet-internal outputs must be decryptable with the wallet's IVK
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

------------     Summary [  34.324s] 1 test run: 0 passed, 1 failed, 328 skipped
        FAIL [  34.323s] libtonode-tests::chain_generics chain_generics::simpool_change_50_000_orchard_to_orchard
error: test run failed1726632509 || (HEAD detached from oscar/lrz_update)[ M ] ef95917c1

this and the preceding 4 commits with error messages, taken together, show
- consistent changes in the error message when unified_spend_key changes
- no change when Some(usk_to_tkey) is replaced with None. thus, tusk is a red herring.

rather, this is a problem with orchard_output_meta in LRZ. orchard_output_meta does nothing for our version of the Trait implementation, so best next step is to delete it bluntly